version: '3.8'

# GDial Backend tjänster
services:
  # Backend API-server
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=${INSTALL_DEV:-false}
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./.env:/app/.env
      - ./dialer.db:/app/dialer.db
    environment:
      - DATABASE_URL=sqlite:///./dialer.db
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3003}
    ports:
      - "${API_PORT:-3003}:3003"
    networks:
      - gdial-network
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3003", "--reload"]

  # Backend CLI-verktyg för testning av samtal
  backend-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - ./config:/app/config
    environment:
      - SQLITE_DB=${SQLITE_DB:-sqlite:///./dialer.db}
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3003}
    networks:
      - gdial-network
    depends_on:
      - backend-api
    profiles:
      - backend-tools
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: ["--help"]

  # Frontend applikation (serveras av Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80" # Mappa värdport (t.ex. 8080) till containerport 80
    networks:
      - gdial-network
    profiles:
      - frontend
    restart: unless-stopped

  # Backend Worker för asynkrona jobb
  backend-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
      - ./dialer.db:/app/dialer.db
    environment:
      - DATABASE_URL=sqlite:///./dialer.db
    networks:
      - gdial-network
    restart: unless-stopped
    command: ["python", "-m", "app.outbox_worker"]
    profiles:
      - backend-workers

networks:
  gdial-network:
    driver: bridge

volumes: {}
